var pt_content = {
		"vertical-menu": "To work on the project use the <strong>horizontal</strong> menu to switch between roles (head, analyst, developer, etc.) and <strong>vertical</strong> menu to work with modules and the system reports relevant to your role.<br /><br />Menu may vary for different <strong>project templates</strong>. You can <strong>customize navigation</strong> in a convenient way.",
		"filter-settings": "Project artifacts: requests, tasks, requirements, etc. are mainly displayed in applications as <strong>lists</strong> or <strong>boards</strong>.<br /><br />We have already set up modules and reports for you, but you can choose to display the required <strong>columns</strong>, select the method of <strong>sorting</strong>, <strong>grouping</strong>, limit the number of rows and etc.<br /><br />Use <strong>filters</strong> to select the necessary data. There are a lot of filters and not all of them are visible on the panel, just turn on the filters you need.<br /><br /><strong>Save</strong> these settings in order to have the data displayed conveniently the next time.",
		"add-favorites": "You can quickly add a useful module to the <strong>Favorites bar</strong> in order&nbsp; to find and open it&nbsp;quickly the next time.<br /><br />You can <strong>save</strong> a configured module <strong>as a report</strong> with a new name and add it to the Favorites bar.",
		"filter-actions": "Here you will find additional features for <strong>export</strong>, import and print of lists and boards elements, as well as for <strong>massive operations</strong> on change of attributes, and <strong>removing</strong> of states and artifacts.",
		"adjust-menu-settings": "Organize <strong>comfortable</strong> workplace: move commonly used modules and reports to the \"Favorites\". You can <strong>change order</strong> of menu items and <strong>group</strong> menu items in the right way.<br /><br />You can customize any sections of the upper <strong>horizontal menu</strong> to adjust it your process. Settings can be easily extended to the <strong>entire </strong>project <strong>team</strong>.",
		"project-settings": "In this section you can add <strong>projects participants</strong>, for they would be able to enter a project, to be tasks performers, to participate in discussions, etc.<br /><br />To adapt the application to one&#039;s projects, he should configure <strong>methodology</strong> options, project <strong>terminology</strong>, references, life cycles of requests, tasks and other artifacts, and add <strong>user</strong> attributes.",
		"project-creation": "This menu allows to switch between <strong>projects</strong>, programs and portfolios.<br /><br />Projects are grouped either by programs or by portfolios, for example, all the projects which you are engaged into are grouped in the \"<strong>My Projects</strong>\" portfolio.</p><p>&nbsp;</p><p>\"<strong>All Projects</strong>\" portfolio allows to synchronize and control the activities of the company. Customization of access to this portfolio is carried out via the administrative section, in the Permissions subsection of the&nbsp;Users section.<br /><br />Create your projects with the use of the most appropriate <strong>templates</strong>.",
		"system-administration": "Creation, editing, and deleting of <strong>users</strong>, deleting of <strong>projects</strong>, configuration of common<strong> directories</strong>, for example, configuration of priorities, roles, etc., as well as whole application inspection, are carried out in the <strong>administrative section</strong>. Only the application administrators can access this section .<br /><br />For more information on Devprom work see the <a href=\"http://devprom.ru/docs\" target=\"_blank\">documentation</a>",
		"my-tasks": "This list displays all tasks <strong>assigned</strong> to you, from all projects you are engaged into.</p><p><br />You can go to the form of a task view, change the status of the task, write off time elapsed, etc.",
		"filters": "To complete your everyday tasks use filters to display the data you need, such as your tasks <strong>assigned</strong>, requests in given <strong>states</strong> or in a particular <strong>release</strong>.<br /><br />Filter settings can be <strong>saved </strong>for the next time.",
		"state-fields": "Add an attribute and specify whether it should be displayed in the form, and whether it must be a mandatory field"
		}; 