imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
framework:
    #esi:            ~
    secret:          123
    router:
        resource: "config/routing.yml"
        strict_requirements: false
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
    session:
        save_path: ~
        name: 'application'
twig:
    exception_controller:  CommonBundle:Exception:show
swiftmailer:
    transport:  smtp
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
monolog:
    handlers:
        applog:
            type: rotating_file
            path: "%kernel.logs_dir%/application.log"
            level: error
            max_files: 5 # Set up to keep log files for 5 recent days only
            channels: ["!mail"]
            include_stacktraces: true
        mail:
            type: rotating_file
            path: "%kernel.logs_dir%/mail.log"
            level: debug
            max_files: 5
            channels: [mail]

