_entry:
    path:  /
    defaults: { _controller: ApplicationBundle:Entry:index }

login:
    path:  /login
    defaults: { _controller: WelcomeBundle:Security:login }
    methods:  GET

login_process_auth:
    path:  /auth
    defaults: { _controller: WelcomeBundle:Security:auth }

sprites:
    path:  /sprite/{filename}
    defaults: { _controller: CommonBundle:Sprite:show }

recovery:
    path:  /recovery
    defaults: { _controller: WelcomeBundle:Security:restore }
    methods:  GET

recovery_process:
    path:  /recovery
    defaults: { _controller: WelcomeBundle:Security:restoreProcess }
    methods:  POST

join:
    path:  /join-project
    defaults: { _controller: WelcomeBundle:Security:join }

openid:
    path:  /openid
    defaults: { _controller: WelcomeBundle:Security:openid }

reset:
    path:  /reset
    defaults: { _controller: WelcomeBundle:Security:reset }
    methods:  GET

reset_process:
    path:  /reset
    defaults: { _controller: WelcomeBundle:Security:resetProcess }
    methods:  POST

error_404:
    path:  /404
    defaults: { _controller: WelcomeBundle:Error:error }

error_500:
    path:  /500
    defaults: { _controller: WelcomeBundle:Error:error }

error_503:
    path:  /503
    defaults: { _controller: WelcomeBundle:Error:error }

logoff:
    path:  /logoff
    defaults: { _controller: ApplicationBundle:Security:logoff }

login_process_success:
    path:  /logged
    defaults: { _controller: WelcomeBundle:Security:authForm }

profile:
    path:  /profile
    defaults: { _controller: ApplicationBundle:Profile:form }
    methods:  GET

profile_notications:
    path:  /notifications
    defaults: { _controller: ApplicationBundle:Profile:notifications }
    methods:  GET

profile_keys:
    path:  /keys
    defaults: { _controller: ApplicationBundle:Profile:keys }
    methods:  GET

app_user_invitation_form:
    path:  /invite
    defaults: { _controller: ApplicationBundle:Invitation:form }

project_new:
    path:  /projects/new
    defaults: { _controller: ApplicationBundle:Project:new }
    methods:  GET

project_create:
    path:  /projects/new
    defaults: { _controller: ApplicationBundle:Project:create }
    methods:  POST

project_welcome:
    path:  /projects/welcome
    defaults: { _controller: ApplicationBundle:Project:welcome }
    methods:  GET

project_navi_tree:
    path:  /projects/tree
    defaults: { _controller: ApplicationBundle:Project:navigationTree }
    methods:  GET

menu_config:
    path:  /menu/config
    defaults: { _controller: ApplicationBundle:Menu:config }
    methods:  GET

error_500_zip:
    path:  /500.zip
    defaults: { _controller: ApplicationBundle:Error:errorZip }

_app_tooltip:
    path:  /tooltip/{classname}/{objects}
    defaults: { _controller: ApplicationBundle:Tooltip:show }

_widgets_shortcuts:
    path:  /widget/shortcut/{language}
    defaults: { _controller: ApplicationBundle:Widget:shortcut }

_widgets_mobileapp:
    path:  /widget/mobile/{language}
    defaults: { _controller: ApplicationBundle:Widget:mobile }

_widgets_support:
    path:  /widget/support/{language}
    defaults: { _controller: ApplicationBundle:Widget:support }

_namespace:
    path:  /{module}/{namespace}
    defaults: { _controller: CommonBundle:Page:module }

_page:
    path:  /{module}/{namespace}/{page}
    defaults: { _controller: CommonBundle:Page:module }

_file:
    path:  /{module}/{namespace}/{page}/{file}
    defaults: { _controller: CommonBundle:Page:module }

_co_scripts:
    path:  /scripts/javascript/
    defaults: { _controller: CommonBundle:Scripts:js }

_scripts:
    path:  /co/scripts/javascript/
    defaults: { _controller: CommonBundle:Scripts:js }

_css:
    path:  /scripts/css/
    defaults: { _controller: CommonBundle:Scripts:css }

_co_css:
    path:  /co/scripts/css/
    defaults: { _controller: CommonBundle:Scripts:css }

_rest_auth:
    type:     rest
    resource: Devprom\WelcomeBundle\Controller\Rest\AuthController
    prefix:   /api/auth/{login}
