_entry:
    path:  /
    defaults: { _controller: ApplicationBundle:Entry:index }

logoff:
    path:  /logoff
    defaults: { _controller: ApplicationBundle:Security:logoff }

news:
    path:  /news/{key}
    defaults: { _controller: ApplicationBundle:Atom:news}

sprites:
    path:  /sprite/{filename}
    defaults: { _controller: CommonBundle:Sprite:show }

login:
    path:  /login
    defaults: { _controller: ApplicationBundle:Security:login }
    methods:  GET

login_process_auth:
    path:  /auth
    defaults: { _controller: ApplicationBundle:Security:loginProcess }

login_process_success:
    path:  /logged
    defaults: { _controller: ApplicationBundle:Security:loginCheck }

recovery:
    path:  /recovery
    defaults: { _controller: ApplicationBundle:Security:restore }
    methods:  GET

recovery_process:
    path:  /recovery
    defaults: { _controller: ApplicationBundle:Security:restoreProcess }
    methods:  POST
    
join:
    path:  /join-project
    defaults: { _controller: ApplicationBundle:Security:join }

reset:
    path:  /reset
    defaults: { _controller: ApplicationBundle:Security:reset }
    methods:  GET

reset_process:
    path:  /reset
    defaults: { _controller: ApplicationBundle:Security:resetProcess }
    methods:  POST

profile:
    path:  /profile
    defaults: { _controller: ApplicationBundle:Profile:form }
    methods:  GET

app_user_invitation_form:
    path:  /invite
    defaults: { _controller: ApplicationBundle:Invitation:form }

project_new:
    path:  /projects/new
    defaults: { _controller: ApplicationBundle:Project:new }
    methods:  GET

project_create:
    path:  /projects/new
    defaults: { _controller: ApplicationBundle:Project:create }
    methods:  POST

project_welcome:
    path:  /projects/welcome
    defaults: { _controller: ApplicationBundle:Project:welcome }
    methods:  GET

menu_config:
    path:  /menu/config
    defaults: { _controller: ApplicationBundle:Menu:config }
    methods:  GET

error_404:
    path:  /404
    defaults: { _controller: ApplicationBundle:Error:error }

error_500:
    path:  /500
    defaults: { _controller: ApplicationBundle:Error:error }

error_500_zip:
    path:  /500.zip
    defaults: { _controller: ApplicationBundle:Error:errorZip }

error_310:
    path:  /310
    defaults: { _controller: ApplicationBundle:Error:error } 

error_503:
    path:  /503
    defaults: { _controller: ApplicationBundle:Error:error }

_app_tooltip:
    path:  /tooltip/{classname}/{objects}
    defaults: { _controller: ApplicationBundle:Tooltip:show }

_namespace:
    path:  /{module}/{namespace}
    defaults: { _controller: CommonBundle:Page:module }

_page:
    path:  /{module}/{namespace}/{page}
    defaults: { _controller: CommonBundle:Page:module }

_file:
    path:  /{module}/{namespace}/{page}/{file}
    defaults: { _controller: CommonBundle:Page:module }

_admin_scripts:
    path:  /co/scripts/javascript/
    defaults: { _controller: CommonBundle:Scripts:js }

_admin_css:
    path:  /co/scripts/css/
    defaults: { _controller: CommonBundle:Scripts:css }
