_entry:
    pattern:  /
    defaults: { _controller: ApplicationBundle:Entry:index }

logoff:
    pattern:  /logoff
    defaults: { _controller: ApplicationBundle:Security:logoff }

news:
    pattern:  /news/{key}
    defaults: { _controller: ApplicationBundle:Atom:news}

login:
    pattern:  /login
    defaults: { _controller: ApplicationBundle:Security:login }
    requirements:
        _method:  GET

login_process:
    pattern:  /login
    defaults: { _controller: ApplicationBundle:Security:loginProcess }
    requirements:
        _method:  POST

recovery:
    pattern:  /recovery
    defaults: { _controller: ApplicationBundle:Security:restore }
    requirements:
        _method:  GET

recovery_process:
    pattern:  /recovery
    defaults: { _controller: ApplicationBundle:Security:restoreProcess }
    requirements:
        _method:  POST
    
join:
    pattern:  /join-project
    defaults: { _controller: ApplicationBundle:Security:join }

reset:
    pattern:  /reset
    defaults: { _controller: ApplicationBundle:Security:reset }
    requirements:
        _method:  GET

reset_process:
    pattern:  /reset
    defaults: { _controller: ApplicationBundle:Security:resetProcess }
    requirements:
        _method:  POST

profile:
    pattern:  /profile
    defaults: { _controller: ApplicationBundle:Profile:form }
    requirements:
        _method:  GET

app_user_invitation_form:
    pattern:  /invite
    defaults: { _controller: ApplicationBundle:Invitation:form }

project_new:
    pattern:  /projects/new
    defaults: { _controller: ApplicationBundle:Project:new }
    requirements:
        _method:  GET

project_create:
    pattern:  /projects/new
    defaults: { _controller: ApplicationBundle:Project:create }
    requirements:
        _method:  POST

project_welcome:
    pattern:  /projects/welcome
    defaults: { _controller: ApplicationBundle:Project:welcome }
    requirements:
        _method:  GET

menu_config:
    pattern:  /menu/config
    defaults: { _controller: ApplicationBundle:Menu:config }
    requirements:
        _method:  GET

error_404:
    pattern:  /404
    defaults: { _controller: ApplicationBundle:Error:error }

error_500:
    pattern:  /500
    defaults: { _controller: ApplicationBundle:Error:error }

error_500_zip:
    pattern:  /500.zip
    defaults: { _controller: ApplicationBundle:Error:errorZip }

error_310:
    pattern:  /310
    defaults: { _controller: ApplicationBundle:Error:error } 

error_503:
    pattern:  /503
    defaults: { _controller: ApplicationBundle:Error:error }

_app_tooltip:
    pattern:  /tooltip/{classname}/{objects}
    defaults: { _controller: ApplicationBundle:Tooltip:show }

_namespace:
    pattern:  /{module}/{namespace}
    defaults: { _controller: CommonBundle:Page:module }

_page:
    pattern:  /{module}/{namespace}/{page}
    defaults: { _controller: CommonBundle:Page:module }

_file:
    pattern:  /{module}/{namespace}/{page}/{file}
    defaults: { _controller: CommonBundle:Page:module }

_admin_scripts:
    pattern:  /co/scripts/javascript/
    defaults: { _controller: CommonBundle:Scripts:js }

_admin_css:
    pattern:  /co/scripts/css/
    defaults: { _controller: CommonBundle:Scripts:css }
   