services:
    mail_transport_logger:
        class: Devprom\ApplicationBundle\Service\Mailer\MailTransportLogger
        arguments:
            $logger: "@logger"
        tags:
            - { name: monolog.logger, channel: mail }
    message_logger:
        class: Devprom\ApplicationBundle\Service\Mailer\MessageLogger
        arguments:
            $logger: "@logger"
        tags:
            - { name: monolog.logger, channel: mail }
