<?php

include 'install/InstallLicenseTypeForm.php';
include 'install/InstallLicenseForm.php';
include 'LicenseForm.php';

class LicensePage extends AdminPage
{
    function getTable()
    {
        $license = getFactory()->getObject('LicenseInstalled');
        	
        if ( array_key_exists('LicenseType', $_REQUEST) && $_REQUEST['LicenseType'] == '' ) {
            return new InstallLicenseTypeForm( $license );
        }
        else
        {
        	$class_name = getFactory()->getClass($_REQUEST['LicenseType']);

            if ( class_exists($class_name) ) {
                $license_it = getFactory()->getObject($class_name);
            }
            else {
                $license_it = $license->getAll();
            }

            if ( array_key_exists('LicenseKey', $_REQUEST) ) {
                return new InstallLicenseForm( $license_it );
            }
            	
            return new LicenseForm( $license_it );
        }
    }

    function getForm()
    {
        return null;
    }

    function render($view = null)
    {
        $user = getFactory()->getObject('cms_User');
        if ( $user->getRecordCount() < 1 ) {
            $user_it = $this->createUser();
            if ( $user_it->getId() > 0 ) {
                exit(header('Location: /reset?key='.$user_it->getResetPasswordKey()));
            }
        }

        return parent::render($view); // TODO: Change the autogenerated stub
    }

    protected function createUser()
    {
        $user = getFactory()->getObject('User');
        $user_it = $user->createCachedIterator(
            array (
                JsonWrapper::decode(
                    file_get_contents(
                        DOCUMENT_ROOT . 'conf/admin.json'
                    )
                )
            )
        );
        if ( $user_it->get('Email') == '' ) return $user_it;

        $user_it = $user->getExact($user->add_parms(
            array (
                'Caption' => $user_it->get('Caption'),
                'Login' => $user_it->get('Login'),
                'Email' => $user_it->get('Email'),
                'IsAdmin' => 'Y',
                'Password' => $user_it->get('Login'),
                'RepeatPassword' => $user_it->get('Login')
            )
        ));

        getFactory()->getCacheService()->invalidate('sessions');
        getSession()->close();
        getSession()->open($user_it);

        return $user_it;
    }
}

