<?php
include_once "AccessPolicyBase.php";

class AccessPolicyPortfolio extends AccessPolicyBase
{
	protected function buildRoles()
	{
		return array( 1 => 0 );
	}
	
 	function getEntityAccess( $action_kind, & $object ) 
 	{
 	    switch ( $object->getClassName() )
 	    {
 	        case 'pm_UserSetting':
 	        case 'Comment':
 	        case 'pm_Activity':
 	        case 'pm_CustomReport':
 	        case 'cms_Report':
			case 'pm_ChangeRequest':
			case 'pm_ChangeRequestTrace':
            case 'pm_Task':
			case 'pm_Question':
			case 'pm_Function':
			case 'pm_Attachment':
            case 'WikiPageFile':
			case 'Tag':
			case 'pm_RequestTag':
			case 'WikiTag':
			case 'pm_Watcher':
			case 'pm_Release':
			case 'pm_Milestone':
			case 'pm_Version':
            case 'pm_Build':
            case 'pm_Environment':
			case 'pm_Invitation':
			case 'BlogPost':
            case 'ObjectChangeLog':
            case 'sm_Person':
            case 'sm_Aim':
            case 'sm_Activity':
            case 'sm_Action':
            case 'pm_Workspace':
            case 'pm_WorkspaceMenu':
            case 'pm_WorkspaceMenuItem':
            case 'pm_DashboardItem':
            case 'pm_ProjectMetric':
            case 'co_ProjectGroup':
            case 'pm_Project':
 	            return true;

 	        case 'pm_Methodology':
 	        case 'pm_AccessRight':
 	        case 'pm_CustomAttribute':
 	            return false;

			case 'pm_Task':
			case 'pm_TaskTrace':
				return $action_kind != ACCESS_CREATE;

 	        default:
				if ( $object instanceof ProjectPage ) return true;
				if ( $object->getVpdValue() == '' ) return true;
 	            return $action_kind == ACCESS_READ;
 	    }
 	    
 	    return parent::getEntityAccess( $action_kind, $object );
 	}

 	function getObjectAccess($action_kind, &$object_it)
    {
        switch( $object_it->object->getEntityRefName() )
        {
            case 'pm_Project':
                if ( $object_it->IsPortfolio() ) {
                    return !in_array($object_it->get('CodeName'), array('my','all')) || $action_kind == ACCESS_READ;
                }
                else {
                    return in_array($action_kind, array(ACCESS_READ, ACCESS_CREATE));
                }
                break;
        }
        return parent::getObjectAccess($action_kind, $object_it); // TODO: Change the autogenerated stub
    }

    function getRoleReferenceName( $role_id )
	{
	    return 'linkedguest';
	}

    public function getAttributeAccess( $action_kind, &$object, $attribute_refname, $reference_class = '' )
    {
        if ( $object->getEntityRefName() == 'pm_Activity' ) {
            switch( $attribute_refname ) {
                case 'Participant':
                    return $action_kind == ACCESS_READ;
            }
        }
        return parent::getAttributeAccess( $action_kind, $object, $attribute_refname, $reference_class = '' );
    }
}
