config:
    pattern: /pm/{project}/menu/{report}
    defaults: { _controller: ProjectBundle:Navigation:index }

settings:
    pattern: /pm/{project}/settings/{area}/{action}
    defaults: { _controller: ProjectBundle:Settings:index }

_broken_trace_explain:
    pattern:  /pm/{project}/tooltip/explain/{object}
    defaults: { _controller: ProjectBundle:Tooltip:explain }

_tooltip:
    pattern:  /pm/{project}/tooltip/{classname}/{objects}
    defaults: { _controller: ProjectBundle:Tooltip:show }

_tooltip_objects_list:
    pattern:  /pm/{project}/tooltip/objectlist/{classname}/{objects}
    defaults: { _controller: ProjectBundle:Tooltip:list }

_treemodel_select:
    pattern:  /pm/{project}/treemodel/{classname}
    defaults: { _controller: ProjectBundle:Tree:index }

_export:
    pattern:  /pm/{project}/export
    defaults: { _controller: ProjectBundle:Project:export }

_scripts:
    pattern:  /pm/{project}/scripts/javascript/
    defaults: { _controller: CommonBundle:Scripts:js }

_css:
    pattern:  /pm/{project}/scripts/css/
    defaults: { _controller: CommonBundle:Scripts:css }

invite:
    pattern:  /pm/{project}/invite
    defaults: { _controller: ProjectBundle:Invitation:form }
    requirements:
        _method:  GET

invite_process:
    pattern:  /pm/{project}/invite
    defaults: { _controller: ProjectBundle:Invitation:formProcess }
    requirements:
        _method:  POST

pages:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\PagesController
    prefix:	  /pm/{project}/menu/rest

menu_nodes:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\NodesController
    prefix:   /pm/{project}/menu/rest/functionalareas/{areaid}

functional_areas:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\FunctionalareasController
    prefix:   /pm/{project}/menu/rest

rest_iteration:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\IterationController
    prefix:   /pm/{project}/api/v1

rest_release:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\ReleaseController
    prefix:   /pm/{project}/api/v1

rest_build:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\BuildController
    prefix:   /pm/{project}/api/v1

rest_issue:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\IssueController
    prefix:   /pm/{project}/api/v1

rest_change:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\ChangeController
    prefix:   /pm/{project}/api/v1

rest_task:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\TaskController
    prefix:   /pm/{project}/api/v1

rest_bug:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\BugController
    prefix:   /pm/{project}/api/v1
    