config:
    pattern: /pm/{project}/menu/{report}
    defaults: { _controller: ProjectBundle:Navigation:index }

_broken_trace_explain:
    pattern:  /pm/{project}/tooltip/explain/{object}
    defaults: { _controller: ProjectBundle:Tooltip:explain }

_tooltip:
    pattern:  /pm/{project}/tooltip/{classname}/{objects}
    defaults: { _controller: ProjectBundle:Tooltip:show }

_tooltip_objects_list:
    pattern:  /pm/{project}/tooltip/objectlist/{classname}/{objects}
    defaults: { _controller: ProjectBundle:Tooltip:list }

_wiki_select:
    pattern:  /pm/{project}/wiki/select/{classname}
    defaults: { _controller: ProjectBundle:Wiki:select }

_export:
    pattern:  /pm/{project}/export
    defaults: { _controller: ProjectBundle:Project:export }

_scripts:
    pattern:  /pm/{project}/scripts/javascript
    defaults: { _controller: ProjectBundle:Scripts:js }

_css:
    pattern:  /pm/{project}/scripts/css
    defaults: { _controller: ProjectBundle:Scripts:css }

pages:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\PagesController
    prefix:	  /pm/{project}/menu/rest

menu_nodes:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\NodesController
    prefix:   /pm/{project}/menu/rest/functionalareas/{areaid}

functional_areas:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\FunctionalareasController
    prefix:   /pm/{project}/menu/rest

rest_iteration:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\IterationController
    prefix:   /pm/{project}/api/v1

rest_release:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\ReleaseController
    prefix:   /pm/{project}/api/v1

rest_build:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\BuildController
    prefix:   /pm/{project}/api/v1

rest_issue:
    type:     rest
    resource: Devprom\ProjectBundle\Controller\Rest\IssueController
    prefix:   /pm/{project}/api/v1
    