<?php
include_once SERVER_ROOT_PATH.'core/methods/ExcelExportWebMethod.php';
include "ServicePayedList.php";

class ServicePayedTable extends PageTable
{
    function getList()
    {
        return new ServicePayedList( $this->getObject() );
    }

    function getActions()
    {
        $actions = parent::getActions(); // TODO: Change the autogenerated stub

        $method = new ExcelExportWebMethod();
        array_push($actions, array( 'name' => $method->getCaption(),
            'url' => $method->getJSCall() ) );

        return $actions;
    }
}
