!define TABLE (T,#FFAAAA)

class "pm_ArtefactType" << TABLE >> {
  Caption: VARCHAR
  IsDisplayedOnSite: CHAR
}

class "pm_Artefact" << TABLE >> {
  Content: FILE
  Caption: VARCHAR
  Kind: INTEGER
  Description: RICHTEXT
  IsAuthorizedDownload: CHAR
  Project: INTEGER
  Participant: INTEGER
  IsArchived: CHAR
  Version: VARCHAR
}

class "pm_Build" << TABLE >> {
  Caption: VARCHAR
  Description: RICHTEXT
  Result: RICHTEXT
  Release: INTEGER
  Version: INTEGER
  IsActual: CHAR
  Application: TEXT
}

class "pm_Subversion" << TABLE >> {
  ConnectorClass: VARCHAR
  Project: INTEGER
  SVNPath: VARCHAR
  RootPath: VARCHAR
  Caption: VARCHAR
  LoginName: VARCHAR
  SVNPassword: PASSWORD
}

class "pm_SubversionRevision" << TABLE >> {
  Project: INTEGER
  Version: TEXT
  VersionNum: INTEGER
  Description: LARGETEXT
  Author: TEXT
  CommitDate: TEXT
  Repository: INTEGER
}

"pm_Artefact" << TABLE >> "*" -- "1" "pm_ArtefactType" << TABLE >> : Kind
"pm_Artefact" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
"pm_Artefact" << TABLE >> "*" -- "1" "pm_Participant" << TABLE >> : Participant
"pm_Build" << TABLE >> "*" -- "0..1" "pm_Release" << TABLE >> : Release
"pm_Build" << TABLE >> "*" -- "0..1" "pm_Version" << TABLE >> : Version
"pm_Subversion" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
"pm_SubversionRevision" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
"pm_SubversionRevision" << TABLE >> "*" -- "1" "pm_Subversion" << TABLE >> : Repository
