!define TABLE (T,#FFAAAA)

class "co_Team" << TABLE >> {
  Caption: VARCHAR
  Tagline: LARGETEXT
  Description: LARGETEXT
  Author: INTEGER
  Rating: FLOAT
  TeamState: INTEGER
}

class "co_TeamUser" << TABLE >> {
  Team: INTEGER
  SystemUser: INTEGER
  TeamRoles: LARGETEXT
  IsActive: CHAR
}

class "co_ProjectSubscription" << TABLE >> {
  SystemUser: INTEGER
  Project: INTEGER
}

class "co_ServiceCategory" << TABLE >> {
  Caption: VARCHAR
}

class "co_Service" << TABLE >> {
  Caption: VARCHAR
  Category: INTEGER
  Description: LARGETEXT
  Cost: LARGETEXT
  Author: INTEGER
  Team: INTEGER
}

class "co_ServiceRequest" << TABLE >> {
  Service: INTEGER
  Customer: INTEGER
  Response: RICHTEXT
  IsClosed: CHAR
}

class "co_IssueOutsourcing" << TABLE >> {
  ChangeRequest: INTEGER
  Project: INTEGER
  Cost: TEXT
  Duration: INTEGER
  Comment: RICHTEXT
}

class "co_OutsourcingSuggestion" << TABLE >> {
  IssueOutsourcing: INTEGER
  Cost: LARGETEXT
  SystemUser: INTEGER
  Comment: RICHTEXT
  IsAccepted: CHAR
}

class "co_AdviseTheme" << TABLE >> {
  Caption: VARCHAR
}

class "co_Advise" << TABLE >> {
  Caption: VARCHAR
  Advise: RICHTEXT
  Theme: INTEGER
  Author: INTEGER
  IsApproved: CHAR
}

class "co_Bill" << TABLE >> {
  SystemUser: INTEGER
  Caption: VARCHAR
}

class "co_BillOperation" << TABLE >> {
  Caption: VARCHAR
  Volume: FLOAT
  Comment: LARGETEXT
  Bill: INTEGER
}

class "co_Rating" << TABLE >> {
  ObjectClass: TEXT
  Rating: INTEGER
}

class "co_RatingVoice" << TABLE >> {
  SystemUser: INTEGER
  IPAddress: TEXT
  Rating: INTEGER
}

class "co_Option" << TABLE >> {
  Caption: VARCHAR
  Cost: FLOAT
  Period: INTEGER
  Period: INTEGER
  Conditions: RICHTEXT
  CodeName: TEXT
}

class "co_OptionUser" << TABLE >> {
  Option: INTEGER
  SystemUser: INTEGER
  IsActive: CHAR
  IsPayed: CHAR
  PaymentDate: DATE
}

class "co_Message" << TABLE >> {
  Subject: TEXT
  Content: LARGETEXT
  Author: INTEGER
  ToUser: INTEGER
  ToTeam: INTEGER
}

class "co_SearchResult" << TABLE >> {
  SearchKind: TEXT
  SystemUser: INTEGER
  Result: LARGETEXT
  Conditions: LARGETEXT
}

class "co_TeamState" << TABLE >> {
  Caption: VARCHAR
  Description: TEXT
}

class "co_CommunityRole" << TABLE >> {
  Caption: VARCHAR
}

class "co_UserRole" << TABLE >> {
  SystemUser: INTEGER
  CommunityRole: INTEGER
}

class "co_ProjectParticipant" << TABLE >> {
  SystemUser: INTEGER
  HourCost: TEXT
  Skills: LARGETEXT
  Tools: LARGETEXT
}

class "co_TenderState" << TABLE >> {
  Caption: VARCHAR
}

class "co_TenderKind" << TABLE >> {
  Caption: VARCHAR
}

class "co_Tender" << TABLE >> {
  Caption: VARCHAR
  Description: RICHTEXT
  Kind: INTEGER
  State: INTEGER
  SystemUser: INTEGER
  Project: INTEGER
}

class "co_TenderAttachment" << TABLE >> {
  Tender: INTEGER
  Attachment: FILE
}

class "co_TenderParticipanceState" << TABLE >> {
  Caption: VARCHAR
}

class "co_TenderParticipant" << TABLE >> {
  Tender: INTEGER
  Team: INTEGER
  State: INTEGER
  Project: INTEGER
}

class "co_RemoteMailbox" << TABLE >> {
  Caption: VARCHAR
  HostAddress: TEXT
  MailboxProvider: INTEGER
  PortServer: INTEGER
  EmailAddress: TEXT
  EmailPassword: PASSWORD
  SenderAddress: VARCHAR
  Project: INTEGER
  UseSSL: CHAR
  UseDebug: CHAR
  IsActive: CHAR
}

"co_Team" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : Author
"co_Team" << TABLE >> "*" -- "1" "co_TeamState" << TABLE >> : TeamState
"co_TeamUser" << TABLE >> "*" -- "1" "co_Team" << TABLE >> : Team
"co_TeamUser" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_ProjectSubscription" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_ProjectSubscription" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
"co_Service" << TABLE >> "*" -- "1" "co_ServiceCategory" << TABLE >> : Category
"co_Service" << TABLE >> "*" -- "0..1" "cms_User" << TABLE >> : Author
"co_Service" << TABLE >> "*" -- "0..1" "co_Team" << TABLE >> : Team
"co_ServiceRequest" << TABLE >> "*" -- "1" "co_Service" << TABLE >> : Service
"co_ServiceRequest" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : Customer
"co_IssueOutsourcing" << TABLE >> "*" -- "1" "pm_ChangeRequest" << TABLE >> : ChangeRequest
"co_IssueOutsourcing" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
"co_OutsourcingSuggestion" << TABLE >> "*" -- "1" "co_IssueOutsourcing" << TABLE >> : IssueOutsourcing
"co_OutsourcingSuggestion" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_Advise" << TABLE >> "*" -- "1" "co_AdviseTheme" << TABLE >> : Theme
"co_Advise" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : Author
"co_Bill" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_BillOperation" << TABLE >> "*" -- "1" "co_Bill" << TABLE >> : Bill
"co_RatingVoice" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_RatingVoice" << TABLE >> "*" -- "1" "co_Rating" << TABLE >> : Rating
"co_OptionUser" << TABLE >> "*" -- "1" "co_Option" << TABLE >> : Option
"co_OptionUser" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_Message" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : Author
"co_Message" << TABLE >> "*" -- "0..1" "cms_User" << TABLE >> : ToUser
"co_Message" << TABLE >> "*" -- "0..1" "co_Team" << TABLE >> : ToTeam
"co_SearchResult" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_UserRole" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_UserRole" << TABLE >> "*" -- "1" "co_CommunityRole" << TABLE >> : CommunityRole
"co_ProjectParticipant" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_Tender" << TABLE >> "*" -- "1" "co_TenderKind" << TABLE >> : Kind
"co_Tender" << TABLE >> "*" -- "1" "co_TenderState" << TABLE >> : State
"co_Tender" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : SystemUser
"co_Tender" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
"co_TenderAttachment" << TABLE >> "*" -- "1" "co_Tender" << TABLE >> : Tender
"co_TenderParticipant" << TABLE >> "*" -- "1" "co_Tender" << TABLE >> : Tender
"co_TenderParticipant" << TABLE >> "*" -- "1" "co_Team" << TABLE >> : Team
"co_TenderParticipant" << TABLE >> "*" -- "1" "co_TenderParticipanceState" << TABLE >> : State
"co_TenderParticipant" << TABLE >> "*" -- "0..1" "pm_Project" << TABLE >> : Project
"co_RemoteMailbox" << TABLE >> "*" -- "1" "co_MailboxProvider" << TABLE >> : MailboxProvider
"co_RemoteMailbox" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
