!define TABLE (T,#FFAAAA)

class "pm_ChangeRequest" << TABLE >> {
  Caption: VARCHAR
  Description: RICHTEXT
  Type: INTEGER
  Environment: INTEGER
  Priority: INTEGER
  Estimation: FLOAT
  State: TEXT
  Function: INTEGER
  Author: INTEGER
  Owner: INTEGER
  Project: INTEGER
  SubmittedVersion: VARCHAR
  ClosedInVersion: VARCHAR
  EstimationLeft: FLOAT
  PlannedRelease: INTEGER
  LifecycleDuration: INTEGER
  StartDate: DATE
  FinishDate: DATE
}

class "pm_Function" << TABLE >> {
  Caption: VARCHAR
  Description: RICHTEXT
  Importance: INTEGER
}

class "pm_ChangeRequestLinkType" << TABLE >> {
  Caption: VARCHAR
  BackwardCaption: VARCHAR
  ReferenceName: VARCHAR
}

class "pm_ChangeRequestLink" << TABLE >> {
  SourceRequest: INTEGER
  TargetRequest: INTEGER
  LinkType: INTEGER
}

class "pm_IssueType" << TABLE >> {
  Caption: VARCHAR
  ReferenceName: VARCHAR
  RelatedColor: COLOR
}

class "pm_Deadline" << TABLE >> {
  Caption: VARCHAR
  Deadline: DATE
  Comment: LARGETEXT
  ChangeRequest: INTEGER
  Milestone: INTEGER
}

class "pm_ChangeRequestTrace" << TABLE >> {
  ChangeRequest: INTEGER
  ObjectId: INTEGER
  ObjectClass: TEXT
  IsActual: CHAR
  Type: VARCHAR
}

class "pm_Importance" << TABLE >> {
  Caption: VARCHAR
  Description: LARGETEXT
}

class "pm_Competitor" << TABLE >> {
  Caption: VARCHAR
  Description: LARGETEXT
}

class "pm_FeatureAnalysis" << TABLE >> {
  Competitor: INTEGER
  Feature: INTEGER
  Strengths: LARGETEXT
  Weaknesses: LARGETEXT
}

class "pm_FunctionTrace" << TABLE >> {
  Feature: INTEGER
  ObjectId: INTEGER
  ObjectClass: TEXT
}

"pm_ChangeRequest" << TABLE >> "*" -- "0..1" "pm_IssueType" << TABLE >> : Type
"pm_ChangeRequest" << TABLE >> "*" -- "0..1" "pm_Environment" << TABLE >> : Environment
"pm_ChangeRequest" << TABLE >> "*" -- "1" "Priority" << TABLE >> : Priority
"pm_ChangeRequest" << TABLE >> "*" -- "0..1" "pm_Function" << TABLE >> : Function
"pm_ChangeRequest" << TABLE >> "*" -- "1" "cms_User" << TABLE >> : Author
"pm_ChangeRequest" << TABLE >> "*" -- "0..1" "pm_Participant" << TABLE >> : Owner
"pm_ChangeRequest" << TABLE >> "*" -- "1" "pm_Project" << TABLE >> : Project
"pm_ChangeRequest" << TABLE >> "*" -- "0..1" "pm_Version" << TABLE >> : PlannedRelease
"pm_Function" << TABLE >> "*" -- "0..1" "pm_Importance" << TABLE >> : Importance
"pm_ChangeRequestLink" << TABLE >> "*" -- "1" "pm_ChangeRequest" << TABLE >> : SourceRequest
"pm_ChangeRequestLink" << TABLE >> "*" -- "1" "pm_ChangeRequest" << TABLE >> : TargetRequest
"pm_ChangeRequestLink" << TABLE >> "*" -- "1" "pm_ChangeRequestLinkType" << TABLE >> : LinkType
"pm_Deadline" << TABLE >> "*" -- "0..1" "pm_ChangeRequest" << TABLE >> : ChangeRequest
"pm_Deadline" << TABLE >> "*" -- "0..1" "pm_Milestone" << TABLE >> : Milestone
"pm_ChangeRequestTrace" << TABLE >> "*" -- "1" "pm_ChangeRequest" << TABLE >> : ChangeRequest
"pm_FeatureAnalysis" << TABLE >> "*" -- "1" "pm_Competitor" << TABLE >> : Competitor
"pm_FeatureAnalysis" << TABLE >> "*" -- "1" "pm_Function" << TABLE >> : Feature
"pm_FunctionTrace" << TABLE >> "*" -- "0..1" "pm_Function" << TABLE >> : Feature
