!define TABLE (T,#FFAAAA)

class "sm_Aim" << TABLE >> {
  Caption: LARGETEXT
  State: TEXT
  Person: INTEGER
}

class "sm_Activity" << TABLE >> {
  Caption: LARGETEXT
  Aim: INTEGER
  State: TEXT
  Estimation: FLOAT
}

class "sm_Action" << TABLE >> {
  Caption: LARGETEXT
  Activity: INTEGER
  State: TEXT
  Estimation: FLOAT
  Kind: INTEGER
}

class "sm_Person" << TABLE >> {
  Caption: VARCHAR
  State: TEXT
  Description: LARGETEXT
  Valuable: LARGETEXT
  Problems: LARGETEXT
  Photo: IMAGE
}

"sm_Aim" << TABLE >> "*" -- "1" "sm_Person" << TABLE >> : Person
"sm_Activity" << TABLE >> "*" -- "1" "sm_Aim" << TABLE >> : Aim
"sm_Action" << TABLE >> "*" -- "1" "sm_Activity" << TABLE >> : Activity
