class "Команда" {
  Название: varchar
  Девиз: largetext
  Описание: largetext
  Автор: Object
  Рейтинг: float
  Статус: Object
}

class "Участие в команде" {
  Команда: Object
  Пользователь: Object
  Роли в команде: largetext
  Принимает участие: char
}

class "Подписка на проект" {
  Пользователь: Object
  Проект: Object
}

class "Категория услуги" {
  Название: varchar
}

class "Услуга" {
  Название: varchar
  Категория: Object
  Описание: largetext
  Стоимость: largetext
  Автор: Object
  Команда: Object
}

class "Заявка на услугу" {
  Услуга: Object
  Заказчик: Object
  Отзыв: richtext
  Закрыта: char
}

class "Аутсорсинг пожелания" {
  Пожелание: Object
  Проект: Object
  Стоимость: text
  Максимальное время реализации, дней: integer
  Комментарий: richtext
}

class "Предложение по реализации" {
  Пожелание: Object
  Стоимость: largetext
  Пользователь: Object
  Комментарий: richtext
  Принято: char
}

class "Тематика совета" {
  Название: varchar
}

class "Совет пользователям" {
  Название: varchar
  Совет: richtext
  Тематика: Object
  Автор: Object
  Утвержден: char
}

class "Счет" {
  Пользователь: Object
  Номер: varchar
}

class "Операция по счету" {
  Название: varchar
  Сумма: float
  Комментарий: largetext
  Счет: Object
}

class "Рейтинг" {
  Класс: text
  Рейтинг: integer
}

class "Голос рейтинга" {
  Пользователь: Object
  Адрес: text
  Рейтинг: Object
}

class "Опция" {
  Название: varchar
  Стоимость: float
  Периодичность оплаты, дн.: integer
  Периодичность: integer
  Условия: richtext
  Кодовое название: text
}

class "Подключение опции" {
  Опция: Object
  Пользователь: Object
  Активна: char
  Оплачена: char
  Дата оплаты: date
}

class "Сообщение" {
  Тема: text
  Текст сообщения: largetext
  Автор: Object
  Получатель пользователь: Object
  Получатель команда: Object
}

class "Результат поиска" {
  Вид поиска: text
  Автор: Object
  Результат: largetext
  Условия поиска: largetext
}

class "Статус команды" {
  Название: varchar
  Описание: text
}

class "Роль в сообществе" {
  Название: varchar
}

class "Роль пользователя" {
  Пользователь: Object
  Роль: Object
}

class "Участник проектов" {
  Пользователь: Object
  Стоимость часа: text
  Профессиональные навыки: largetext
  Владение инструментами: largetext
}

class "Состояние тендера" {
  Название: varchar
}

class "Тип тендера" {
  Название: varchar
}

class "Тендер" {
  Название проекта: varchar
  Краткое описание: richtext
  Тип: Object
  Состояние: Object
  Автор: Object
  Проект: Object
}

class "Приложение к тендеру" {
  Тендер: Object
  Файл: file
}

class "Состояние участия в тендере" {
  Название: varchar
}

class "Участник тендера" {
  Тендер: Object
  Команда: Object
  Состояние: Object
  Проект: Object
}

class "Почтовый ящик" {
  Назначение: varchar
  Почтовый сервер: text
  Способ подключения: Object
  Порт сервера: integer
  Почтовый ящик: text
  Пароль на почтовый ящик: password
  Адрес отправителя: varchar
  Связанный проект: Object
  Использовать SSL/TLS: char
  Использовать режим отладки: char
  Активен: char
}

"Команда" "*" -- "1" "Пользователь": Автор
"Команда" "*" -- "1" "Статус команды": Статус
"Участие в команде" "*" -- "1" "Команда": Команда
"Участие в команде" "*" -- "1" "Пользователь": Пользователь
"Подписка на проект" "*" -- "1" "Пользователь": Пользователь
"Подписка на проект" "*" -- "1" "Проект": Проект
"Услуга" "*" -- "1" "Категория услуги": Категория
"Услуга" "*" -- "0..1" "Пользователь": Автор
"Услуга" "*" -- "0..1" "Команда": Команда
"Заявка на услугу" "*" -- "1" "Услуга": Услуга
"Заявка на услугу" "*" -- "1" "Пользователь": Заказчик
"Аутсорсинг пожелания" "*" -- "1" "Пожелание": Пожелание
"Аутсорсинг пожелания" "*" -- "1" "Проект": Проект
"Предложение по реализации" "*" -- "1" "Аутсорсинг пожелания": Пожелание
"Предложение по реализации" "*" -- "1" "Пользователь": Пользователь
"Совет пользователям" "*" -- "1" "Тематика совета": Тематика
"Совет пользователям" "*" -- "1" "Пользователь": Автор
"Счет" "*" -- "1" "Пользователь": Пользователь
"Операция по счету" "*" -- "1" "Счет": Счет
"Голос рейтинга" "*" -- "1" "Пользователь": Пользователь
"Голос рейтинга" "*" -- "1" "Рейтинг": Рейтинг
"Подключение опции" "*" -- "1" "Опция": Опция
"Подключение опции" "*" -- "1" "Пользователь": Пользователь
"Сообщение" "*" -- "1" "Пользователь": Автор
"Сообщение" "*" -- "0..1" "Пользователь": Получатель пользователь
"Сообщение" "*" -- "0..1" "Команда": Получатель команда
"Результат поиска" "*" -- "1" "Пользователь": Автор
"Роль пользователя" "*" -- "1" "Пользователь": Пользователь
"Роль пользователя" "*" -- "1" "Роль в сообществе": Роль
"Участник проектов" "*" -- "1" "Пользователь": Пользователь
"Тендер" "*" -- "1" "Тип тендера": Тип
"Тендер" "*" -- "1" "Состояние тендера": Состояние
"Тендер" "*" -- "1" "Пользователь": Автор
"Тендер" "*" -- "1" "Проект": Проект
"Приложение к тендеру" "*" -- "1" "Тендер": Тендер
"Участник тендера" "*" -- "1" "Тендер": Тендер
"Участник тендера" "*" -- "1" "Команда": Команда
"Участник тендера" "*" -- "1" "Состояние участия в тендере": Состояние
"Участник тендера" "*" -- "0..1" "Проект": Проект
"Почтовый ящик" "*" -- "1" "Тип почтового ящика": Способ подключения
"Почтовый ящик" "*" -- "1" "Проект": Связанный проект
