class "Комментарий" {
  Содержание: largetext
  Автор: Object
  Объект: integer
  Класс объекта: text
  Предыдущий комментарий: Object
  Внешний автор: text
  E-mail внешнего автора: text
}

class "Тэг" {
  Название: varchar
  Владелец: Object
}

class "Приложение" {
  Файл: file
  Описание: largetext
  Объект: integer
  Класс объект: text
}

class "Снимок" {
  Ид объекта: text
  Класс объекта: text
  Название: varchar
  Автор: Object
  Список: text
  Тип: text
  Описание: largetext
}

class "Элемент снимка" {
  Снимок: Object
  Ид объекта: integer
  Класс объекта: text
}

class "Значение элемента снимка" {
  Элемент снимка: Object
  Название атрибута: varchar
  Ссылочное имя атрибута: varchar
  Значение атрибута: text
}

class "Хеш идентификаторов" {
  Хеш значение: text
  Идентификаторы: richtext
}

class "Пользовательский тэг" {
  Тэг: Object
  Ид объекта: integer
  Класс объекта: varchar
}

"Комментарий" "*" -- "1" "Пользователь": Автор
"Комментарий" "*" -- "0..1" "Комментарий": Предыдущий комментарий
"Тэг" "*" -- "0..1" "Участник": Владелец
"Снимок" "*" -- "1" "Пользователь": Автор
"Элемент снимка" "*" -- "1" "Снимок": Снимок
"Значение элемента снимка" "*" -- "1" "Элемент снимка": Элемент снимка
"Пользовательский тэг" "*" -- "1" "Тэг": Тэг
