class "Метрики итерации" {
  Релиз: Object
  Дата сбора метрик: date
  Загрузка задачами: integer
  Остаточная трудоемкость: integer
  Прошло дней: integer
  Планируемая загрузка: integer
  Тип задачи: Object
}

class "Метрика участника" {
  Участник: Object
  Итерация: Object
  Метрика: text
  Значение метрики: float
}

class "Метрика итерации" {
  Итерация: Object
  MetricValueDate: datetime
  Метрика: text
  Значение метрики: float
}

class "Метрика релиза" {
  Релиз: Object
  MetricValueDate: datetime
  Метрика: text
  Значение метрики: float
}

class "Берндаун релиза" {
  Версия: Object
  Дата метрики: date
  Фактическая загрузка: float
  Прошло дней: integer
  Плановая загрузка: float
}

"Метрики итерации" "*" -- "1" "Итерация": Релиз
"Метрики итерации" "*" -- "0..1" "Тип задачи": Тип задачи
"Метрика участника" "*" -- "1" "Участник": Участник
"Метрика участника" "*" -- "1" "Итерация": Итерация
"Метрика итерации" "*" -- "1" "Итерация": Итерация
"Метрика релиза" "*" -- "1" "Релиз": Релиз
"Берндаун релиза" "*" -- "1" "Релиз": Версия
