class "Итерация" {
  Название: varchar
  Текущая: char
  Черновой вариант: char
  Описание: richtext
  Проект: Object
  Дата начала: date
  Дата окончания: date
  Начальная скорость: integer
  Релиз: Object
  Актуальна: char
  Стадия процесса: Object
}

class "Задача" {
  Название: richtext
  Планируемая трудоемкость, ч.: float
  Исполнитель: Object
  Итерация: Object
  Тип: Object
  Приоритет: Object
  Пожелание: Object
  Проверяющий: Object
  Оставшаяся трудоемкость, ч.: float
  Результат: largetext
  Комментарий: richtext
  Состояние: text
  Дата начала: date
  Дата окончания: date
}

class "Тип задачи" {
  Название: varchar
  Краткое название: varchar
  Описание: largetext
  Цвет: color
  Категория: varchar
  Роль в проекте: Object
  Базовый тип: Object
  Используется при планировании: char
}

class "Релиз" {
  Номер: varchar
  Описание: largetext
  Дата начала: date
  Дата окончания: date
  Проект: Object
  Погрешность оценки, %: integer
  Процент ошибок, %: integer
  Актуален: char
  Начальная скорость: integer
}

class "Веха" {
  Дата: date
  Название: varchar
  Описание: richtext
  Пройдена: char
  Причина изменения даты: richtext
  Результат завершения: richtext
}

class "Активность" {
  Название: varchar
  Дата: date
  Задача: Object
  Затрачено, ч.: float
  Участник: Object
  Описание: text
  Завершена: char
  Итерация: Object
}

class "Трассировка задачи" {
  Задача: Object
  Ид объекта: integer
  Класс объекта: text
  Актуальна: char
}

"Итерация" "*" -- "1" "Проект": Проект
"Итерация" "*" -- "1" "Релиз": Релиз
"Итерация" "*" -- "0..1" "Стадия процесса": Стадия процесса
"Задача" "*" -- "1" "Участник": Исполнитель
"Задача" "*" -- "0..1" "Итерация": Итерация
"Задача" "*" -- "1" "Тип задачи": Тип
"Задача" "*" -- "1" "Приоритет": Приоритет
"Задача" "*" -- "0..1" "Пожелание": Пожелание
"Задача" "*" -- "0..1" "Участник": Проверяющий
"Тип задачи" "*" -- "1" "Роль в проекте": Роль в проекте
"Тип задачи" "*" -- "1" "Тип задачи": Базовый тип
"Релиз" "*" -- "1" "Проект": Проект
"Активность" "*" -- "0..1" "Задача": Задача
"Активность" "*" -- "0..1" "Участник": Участник
"Активность" "*" -- "0..1" "Итерация": Итерация
"Трассировка задачи" "*" -- "1" "Задача": Задача
