class "Цель" {
  Описание: largetext
  Состояние: text
  Персона: Object
}

class "Активность" {
  Описание: largetext
  Цель: Object
  Состояние: text
  Оценка: float
}

class "Действие" {
  Описание: largetext
  Активность: Object
  Состояние: text
  Оценка: float
  Тип действия: integer
}

class "Персона" {
  Имя: varchar
  Состояние: text
  Описание: largetext
  Ценности: largetext
  Проблемы: largetext
  Фотография: image
}

"Цель" "*" -- "1" "Персона": Персона
"Активность" "*" -- "1" "Цель": Цель
"Действие" "*" -- "1" "Активность": Активность
