class "Wiki страница" {
  Путь к родительской странице: text
  Номер раздела: varchar
  Название: varchar
  Ссылочное имя: varchar
  Содержание: largetext
  Родительская страница: Object
  Проект: Object
  Автор: Object
  Пользовательское поле 1: text
  Является шаблоном: integer
  Пользовательское поле 2: text
  В архиве: char
  Пользовательское поле 3: text
  Черновик: char
  Пользовательское поле 3: text
  Редактор содержимого: text
  Состояние: text
  Тип страницы: Object
}

class "Файл страницы" {
  Название: varchar
  Файл: file
  Описание: varchar
  Страница: Object
}

class "Изменение страницы Wiki" {
  Страница: Object
  Содержание: largetext
  Автор: Object
}

class "Блог" {
  Название: varchar
}

class "Сообщение блога" {
  Заголовок: varchar
  Содержание: text
  Автор: integer
  Блог: Object
  Опубликовано: char
  Редактор содержимого: text
}

class "Файл сообщения блога" {
  Название: varchar
  Описание: largetext
  Файл: file
  Сообщение блога: Object
}

class "Тэг Wiki страницы" {
  Wiki страница: Object
  Тэг: Object
  Тип Wiki страницы: text
}

class "Тэг сообщения блога" {
  Сообщение блога: Object
  Тэг: Object
}

class "Наблюдатель" {
  Ид объекта: integer
  Класс объекта: text
  Пользователь: Object
  Адрес электронной почты: text
}

class "Тип страницы" {
  Название: varchar
  Краткое название: varchar
  Описание: largetext
  Ссылочное имя: varchar
  text(937): Object
  Редактор страниц: text
  Ссылочное имя страницы: varchar
}

class "Трассировка страницы" {
  Исходная страницы: Object
  Целевая страница: Object
  Связь актуальна: char
  Ревизия: Object
  Тип: text
  Причина рассинхронизации: varchar
}

"Wiki страница" "*" -- "0..1" "Wiki страница": Родительская страница
"Wiki страница" "*" -- "1" "Проект": Проект
"Wiki страница" "*" -- "1" "Участник": Автор
"Wiki страница" "*" -- "0..1" "Тип страницы": Тип страницы
"Файл страницы" "*" -- "1" "Wiki страница": Страница
"Изменение страницы Wiki" "*" -- "1" "Wiki страница": Страница
"Изменение страницы Wiki" "*" -- "1" "Участник": Автор
"Сообщение блога" "*" -- "1" "Блог": Блог
"Файл сообщения блога" "*" -- "1" "Сообщение блога": Сообщение блога
"Тэг Wiki страницы" "*" -- "1" "Wiki страница": Wiki страница
"Тэг Wiki страницы" "*" -- "1" "Тэг": Тэг
"Тэг сообщения блога" "*" -- "1" "Сообщение блога": Сообщение блога
"Тэг сообщения блога" "*" -- "1" "Тэг": Тэг
"Наблюдатель" "*" -- "1" "Пользователь": Пользователь
"Тип страницы" "*" -- "0..1" "Wiki страница": text(937)
"Трассировка страницы" "*" -- "1" "Wiki страница": Исходная страницы
"Трассировка страницы" "*" -- "1" "Wiki страница": Целевая страница
"Трассировка страницы" "*" -- "0..1" "Снимок": Ревизия
