class "Методология" {
  Использовать планирование задач: char
  text(1716): char
  Использовать планирование релизов: varchar
  Использовать итерации фиксированной длительности: char
  Длительность итерации в неделях: integer
  Используется управление вехами проекта: char
  Использовать управление версиями: char
  Использовать ежедневные митинги: char
  Использовать фазу проектирования: char
  Использовать фазу подготовки требований: char
  Использовать фазу тестирования: char
  Проект: Object
  Использовать фазу подготовки справочной документации: char
  text(1033): char
  Требуется утверждение пожеланий: char
  Закреплять ответственного за пожеланием: char
  Использовать декомпозицию по функциям: char
  Закреплять ответственных за высокоуровневыми функциями: char
  Используется несколько окружений: char
  Разрешать отклонения от методологии: char
  text(1365): char
  Оценка трудоемкости: varchar
  Участники отчитываются о затраченном времени: char
  Участники выбирают себе задачи самостоятельно: char
  Отслеживать сроки выполнения задач и реализации пожеланий: char
  Определять порядок следования задач: char
  Использовать перекрестную проверку задач: char
  Среднее время проверки выполненной задачи, ч.: integer
  Заказчик принимает участие в проекте: char
  Заказчик выполняет приемку пожеланий: char
  text(kanban14): char
  text(storymapping10): char
}

class "Шаблон - HTML" {
  Название: varchar
  Описание: richtext
  Стили (CSS): largetext
  Верхний колонтитул: largetext
  Нижний колонтитул: largetext
  С оглавлением в начале страницы: char
  Нумеровать разделы: char
}

class "Право доступа" {
  Проектная роль: Object
  Объект: varchar
  Тип объекта: text
  Доступ: text
}

class "Настройки версии" {
  Проект: Object
  Включать номер релиза: char
  Включать номер итерации: char
  Включать номер сборки: char
}

class "Связанный проект" {
  Проект: Object
  Проект: Object
  Пожелания и функции: integer
  text(ee207): integer
  Итерации и задачи: integer
  База знаний: integer
  Блог: integer
  Требования: integer
  Тестовая документация: integer
  Справочная документация: integer
  Файлы: integer
  Исходный код: integer
}

class "Доступ к объекту" {
  Класс: text
  Объект: integer
  Роль в проекте: Object
  Доступ: text
}

class "Стадия процесса" {
  Название: varchar
  Описание: largetext
}

class "Тип задачи в стадии процесса" {
  Тип задачи: Object
  Стадия процесса: Object
}

class "Пользовательский отчет" {
  Название: varchar
  Категория: text
  Модуль: varchar
  Базовый отчет: text
  Параметры: text
  Добавить в избранное: char
  Описание: largetext
  Автор: Object
}

class "Настройка пользователя" {
  Настройка: text
  Значение: text
  Участник: Object
}

class "Пользовательский атрибут" {
  Название: varchar
  Ссылочное имя: varchar
  Сущность: varchar
  Тип: integer
  Варианты значений: largetext
  Значение по умолчанию: varchar
  Описание: largetext
  Видимо на форме: char
  Обязательно для заполнения: char
  Является уникальным: char
  Дискриминатор: text
  Имя класса ссылки: varchar
  Мощность: integer
}

class "Значение атрибута" {
  Пользовательский атрибут: Object
  Идентификатор объекта: integer
  Значение: число: integer
  Значение: текст: text
  Значение: текст: largetext
  Значение: пароль: password
}

"Методология" "*" -- "1" "Проект": Проект
"Право доступа" "*" -- "1" "Роль в проекте": Проектная роль
"Настройки версии" "*" -- "1" "Проект": Проект
"Связанный проект" "*" -- "1" "Проект": Проект
"Связанный проект" "*" -- "1" "Проект": Проект
"Доступ к объекту" "*" -- "1" "Роль в проекте": Роль в проекте
"Тип задачи в стадии процесса" "*" -- "1" "Тип задачи": Тип задачи
"Тип задачи в стадии процесса" "*" -- "1" "Стадия процесса": Стадия процесса
"Пользовательский отчет" "*" -- "1" "Пользователь": Автор
"Настройка пользователя" "*" -- "1" "Участник": Участник
"Значение атрибута" "*" -- "1" "Пользовательский атрибут": Пользовательский атрибут
