class "Каталог" {
  Название: varchar
  Отображается на сайте: char
}

class "Файл" {
  Файл: file
  Название: varchar
  Каталог: Object
  Описание: richtext
  Требуется авторизация для скачивания: char
  Проект: Object
  Выложил: Object
  В архиве: char
  Версия: varchar
}

class "Сборка" {
  Номер: varchar
  Комментарий: richtext
  Результат проверки: richtext
  Релиз: Object
  Релиз: Object
  Актуальна: char
  Приложение: text
}

class "text(1058)" {
  text(1059): varchar
  Проект: Object
  Путь к репозиторию: varchar
  Путь к файлам: varchar
  Краткое название: varchar
  Имя пользователя: varchar
  Пароль: password
}

class "text(1060)" {
  Проект: Object
  Версия: text
  Версия: integer
  Описание: largetext
  Автор: text
  Дата: text
  Репозиторий: Object
}

"Файл" "*" -- "1" "Каталог": Каталог
"Файл" "*" -- "1" "Проект": Проект
"Файл" "*" -- "1" "Участник": Выложил
"Сборка" "*" -- "0..1" "Итерация": Релиз
"Сборка" "*" -- "0..1" "Релиз": Релиз
"text(1058)" "*" -- "1" "Проект": Проект
"text(1060)" "*" -- "1" "Проект": Проект
"text(1060)" "*" -- "1" "text(1058)": Репозиторий
