class "Участник" {
  Пользователь: Object
  Имя: varchar
  Средняя загрузка в день, ч.: integer
  Перекрыть атрибуты пользователя: char
  E-mail: text
  ICQ: text
  Skype: text
  Дом. тел.: text
  Моб. тел.: text
  Логин: text
  Проект: Object
  Принимает участие в проекте: char
  Оплата: float
}

class "Участие в проекте" {
  Участник: Object
  Ежедневная загрузка, ч.: float
  Проект: Object
  Роль в проекте: Object
}

class "Проект" {
  Название: varchar
  Кодовое название: text
  Описание: richtext
  Язык проекта: Object
  Платформа: largetext
  Несколько конфигураций программного продукта: char
  Главная страница: Object
  Страница требований: Object
  Дата начала: date
  Дата окончания: date
  Проект закрыт: char
  Блог проекта: Object
  Инструментарий: largetext
  Рейтинг: float
  Является тендером: char
  text(sourcecontrol8): char
  Выкладывать файлы проекта: char
  Назначаются встречи с участниками проекта: char
  Проводятся опросы мнений участников: char
  В проекте используется база знаний: char
  Ведется блог проекта: char
  Редактор документов: text
  text(1024): integer
}

class "Роль в проекте" {
  Название: varchar
  Описание: largetext
  Кодовое название: varchar
  Базовая роль: Object
}

class "Почтовое сообщение" {
  Адресат: Object
  Тема: largetext
  Содержание: largetext
  Отправитель: Object
}

class "Вопрос" {
  Содержание: richtext
  Автор: Object
  Состояние: text
}

class "Отчет" {
  Название: varchar
  Описание: text
  URL: text
  Категория: Object
}

class "Категория отчета" {
  Название: varchar
  Ссылочное имя: varchar
}

"Участник" "*" -- "1" "Пользователь": Пользователь
"Участник" "*" -- "1" "Проект": Проект
"Участие в проекте" "*" -- "1" "Участник": Участник
"Участие в проекте" "*" -- "1" "Проект": Проект
"Участие в проекте" "*" -- "1" "Роль в проекте": Роль в проекте
"Проект" "*" -- "0..1" "Язык": Язык проекта
"Проект" "*" -- "0..1" "Wiki страница": Главная страница
"Проект" "*" -- "0..1" "Wiki страница": Страница требований
"Проект" "*" -- "1" "Блог": Блог проекта
"Роль в проекте" "*" -- "1" "Роль в проекте": Базовая роль
"Почтовое сообщение" "*" -- "1" "Участник": Адресат
"Почтовое сообщение" "*" -- "1" "Участник": Отправитель
"Вопрос" "*" -- "1" "Пользователь": Автор
"Отчет" "*" -- "1" "Категория отчета": Категория
