class "Приоритет" {
  Название: varchar
  Цвет: color
}

class "Изменение объекта" {
  Название объекта: varchar
  Имя класса: varchar
  Ид объекта: integer
  Класс объекта: text
  Url объекта: text
  Название сущности: text
  Тип: text
  Содержание: largetext
  Автор: text
  Уровень видимости: integer
  Пользователь: Object
}

class "Шаблон проекта" {
  Название: varchar
  Описание: largetext
  Имя файла: text
  Язык шаблона: Object
  Используется по умолчанию: char
  Редакция: text
}

"Изменение объекта" "*" -- "0..1" "Пользователь": Пользователь
"Шаблон проекта" "*" -- "1" "Язык": Язык шаблона
