class "Пожелание" {
  Название: varchar
  Описание: richtext
  Тип: Object
  Окружение: Object
  Приоритет: Object
  Трудоемкость: float
  Состояние: text
  Функция: Object
  Автор: Object
  Исполнитель: Object
  Проект: Object
  Обнаружено в: varchar
  Выполнено в: varchar
  Оставшаяся трудоемкость: float
  Релиз: Object
  Продолжительность цикла, ч.: integer
  Дата начала: date
  Дата окончания: date
}

class "Функция" {
  Название: varchar
  Описание: richtext
  Важность: Object
}

class "Тип связи пожеланий" {
  Название: varchar
  Обратное название: varchar
  Кодовое название: varchar
}

class "Связь с пожеланиями" {
  Исходное пожелание: Object
  Целевое пожелание: Object
  Тип связи: Object
}

class "Тип пожелания" {
  Название: varchar
  Ссылочное имя: varchar
  Цвет: color
}

class "Срок" {
  Цель: varchar
  Дата: date
  Комментарий: largetext
  Пожелание: Object
  Веха: Object
}

class "Трассировка пожелания" {
  Пожелание: Object
  Ид объекта: integer
  Класс: text
  Актуальна: char
  Тип связи: varchar
}

class "Важность" {
  Название: varchar
  Описание: largetext
}

class "Конкурирующий продукт" {
  Название: varchar
  Описание: largetext
}

class "Анализ функции продукта" {
  Продукт: Object
  Функция: Object
  Сильные стороны: largetext
  Слабые стороны: largetext
}

class "Трассировка функции" {
  Функция: Object
  Ид объекта: integer
  Класс объекта: text
}

"Пожелание" "*" -- "0..1" "Тип пожелания": Тип
"Пожелание" "*" -- "0..1" "Окружение": Окружение
"Пожелание" "*" -- "1" "Приоритет": Приоритет
"Пожелание" "*" -- "0..1" "Функция": Функция
"Пожелание" "*" -- "1" "Пользователь": Автор
"Пожелание" "*" -- "0..1" "Участник": Исполнитель
"Пожелание" "*" -- "1" "Проект": Проект
"Пожелание" "*" -- "0..1" "Релиз": Релиз
"Функция" "*" -- "0..1" "Важность": Важность
"Связь с пожеланиями" "*" -- "1" "Пожелание": Исходное пожелание
"Связь с пожеланиями" "*" -- "1" "Пожелание": Целевое пожелание
"Связь с пожеланиями" "*" -- "1" "Тип связи пожеланий": Тип связи
"Срок" "*" -- "0..1" "Пожелание": Пожелание
"Срок" "*" -- "0..1" "Веха": Веха
"Трассировка пожелания" "*" -- "1" "Пожелание": Пожелание
"Анализ функции продукта" "*" -- "1" "Конкурирующий продукт": Продукт
"Анализ функции продукта" "*" -- "1" "Функция": Функция
"Трассировка функции" "*" -- "0..1" "Функция": Функция
