class "Ошибка" {
  Название: varchar
  Описание: richtext
  Бизнес приоритет: Object
  Окружение: Object
  Релиз: Object
  Сборка: Object
  Исходное пожелание: Object
  Требование: Object
  Файл: file
  Состояние: text
  Обнаружил: Object
  Проект: Object
  Запланировано: char
  Тест: Object
  Проверка тестового случая: Object
}

class "Доработка" {
  Название: varchar
  Описание: richtext
  Бизнес приоритет: Object
  Исходное пожелание: Object
  Требование: Object
  Составитель: Object
  Файл: file
  Проект: Object
  Запланировано: char
  Проверка тестового случая: Object
}

class "pm_Task" {
}

class "Митинг" {
  Тема: largetext
  Повестка: richtext
  Место: text
  Дата: date
  Время: text
  Напомнить: integer
}

class "Участие в митинге" {
  Митинг: Object
  Участник: Object
  Комментарий: largetext
  Accepted: char
  Отклонено: char
  Причина отклонения: largetext
  Напомнить: integer
}

class "Состояние работы" {
  Название: varchar
}

class "Создание проекта" {
  IP адрес: text
  Проект: Object
  Кодовое название: text
  Язык проекта: text
  Название: varchar
  Логин: text
  Email: text
  Пароль: text
  Методология: text
  Хеш создания: text
  Язык проекта: text
  Публичность: text
  Пользователь: Object
}

class "Использование проекта" {
  Проект: Object
  Участник: Object
  Ид сессии: text
  Дата последнего входа: date
  Временная зона: varchar
}

class "Справка" {
  Название: varchar
  Описание: largetext
  Версия: varchar
  Содержание: Object
  Проект: Object
}

class "Связь со справочной документацией" {
}

class "Причина деактуализации справочной документации " {
  Связь со справочной документацией: Object
  Задача: Object
  Активна: char
}

class "Публикация проекта" {
  Проект: Object
  Публиковать проект: char
  Публиковать страницу ввода пожеланий: char
  Публиковать сведения об участниках проекта: char
  Публиковать блог проекта: char
  Публиковать домашнюю страницу проекта: char
  Публиковать информацию о релизах проекта: char
  Публиковать документацию: char
  Публиковать артефакты: char
}

class "Шаблон - HTML" {
  Название: varchar
  Итерация: richtext
  Стили (CSS): largetext
  Верхний колонтитул: largetext
  Нижний колонтитул: largetext
  С оглавлением в начале страницы: char
  Нумеровать разделы: char
}

class "Связь задачи и сборки" {
  Сборка: Object
  Задача: Object
}

class "Тэг пожелания" {
  Пожелание: Object
  Тэг: Object
}

class "Конфигурация программного продукта" {
  Название: varchar
  Особенности конфигурации: richtext
}

class "Новостной канал" {
  Название: varchar
  Описание: text
  Ссылка (RSS): text
  Язык: Object
  Публичный: char
}

class "Позиция в новостном канале" {
  Заголовок: varchar
  Описание: text
  Ссылка: text
  Новостной канал: Object
}

class "Подписка проекта на новости" {
  Новостной канал: Object
  Проект: Object
}

class "Ежедневный митинг" {
  Что я сделал вчера?: richtext
  Что я планирую сделать сегодня?: richtext
  Текущие проблемы: richtext
  Участник: Object
}

class "Участие в митинге" {
  Митинг: Object
  Участник: Object
  Подтверждено: char
  Отклонено: float
  Причина отклонения: float
  Напомнить: integer
}

class "Заметка к релизу" {
  Релиз: Object
  Пожелание: Object
  Заметка: largetext
}

class "Связь теста с требованием" {
}

class "Опросник" {
  Название: varchar
  Описание: largetext
  Публичный: char
}

class "Позиция опросника" {
  Название: varchar
  Варианты ответов: largetext
  Является разделом: char
  Опрос: Object
}

class "Результат опроса" {
  Опрос: Object
  Пользователь: Object
  Текущий: char
  Дата завершения: date
  Хеш пользователя: text
}

class "Позиция результата опроса" {
  Позиция опросника: Object
  Результат опроса: Object
  Ответ: largetext
}

class "Состояние требования" {
  Название: varchar
}

class "Тэг проекта" {
  Название: varchar
  Проект: Object
}

class "Вакансия в проекте" {
  Роль в проекте: varchar
  Проект: Object
  Активна: char
  Требуемая занятость, часов в день: integer
  Оплата часа работы: text
  Описание: richtext
  Дополнительные требования: richtext
}

class "Приглашение в проект" {
  Проект: Object
  Автор: Object
  Адресат: text
}

class "Загрузка артефакта" {
  Название: varchar
  Идентификатор: integer
  Сущность: text
}

class "Загрузивший пользователь" {
  Пользователь: Object
  Загрузка артефакта: Object
}

class "Валюта" {
  Название: varchar
  Кодовое значение: text
}

class "Настройки бюджетирования" {
  Проект: Object
  Использовать бюджетирование в проекте: char
  Валюта проекта: Object
  Модель оплаты: Object
  Скрывать стоимость работ участников: char
}

class "Модель оплаты" {
  Название: varchar
}

class "Изменение сообщения блога" {
  Сообщение блога: Object
  Содержание: largetext
  Автор: Object
}

class "Интервал календаря" {
  Тип: text
  Дата начала: date
  Дата окончания: date
  Год: integer
  Месяц: integer
  День: integer
  Название: varchar
  Квартал: integer
  Неделя: integer
}

"Ошибка" "*" -- "1" "Приоритет": Бизнес приоритет
"Ошибка" "*" -- "0..1" "Окружение": Окружение
"Ошибка" "*" -- "1" "Итерация": Релиз
"Ошибка" "*" -- "0..1" "Сборка": Сборка
"Ошибка" "*" -- "0..1" "Пожелание": Исходное пожелание
"Ошибка" "*" -- "1" "Wiki страница": Требование
"Ошибка" "*" -- "1" "Участник": Обнаружил
"Ошибка" "*" -- "1" "Проект": Проект
"Ошибка" "*" -- "0..1" "Тест": Тест
"Ошибка" "*" -- "0..1" "Проверка тестового случая": Проверка тестового случая
"Доработка" "*" -- "1" "Приоритет": Бизнес приоритет
"Доработка" "*" -- "0..1" "Пожелание": Исходное пожелание
"Доработка" "*" -- "0..1" "Wiki страница": Требование
"Доработка" "*" -- "1" "Участник": Составитель
"Доработка" "*" -- "1" "Проект": Проект
"Доработка" "*" -- "0..1" "Проверка тестового случая": Проверка тестового случая
"Участие в митинге" "*" -- "1" "Митинг": Митинг
"Участие в митинге" "*" -- "1" "Участник": Участник
"Создание проекта" "*" -- "1" "Проект": Проект
"Создание проекта" "*" -- "1" "Пользователь": Пользователь
"Использование проекта" "*" -- "1" "Проект": Проект
"Использование проекта" "*" -- "1" "Пользователь": Участник
"Справка" "*" -- "0..1" "Wiki страница": Содержание
"Справка" "*" -- "1" "Проект": Проект
"Причина деактуализации справочной документации " "*" -- "0..1" "Связь со справочной документацией": Связь со справочной документацией
"Причина деактуализации справочной документации " "*" -- "0..1" "Задача": Задача
"Публикация проекта" "*" -- "1" "Проект": Проект
"Связь задачи и сборки" "*" -- "1" "Сборка": Сборка
"Связь задачи и сборки" "*" -- "1" "Задача": Задача
"Тэг пожелания" "*" -- "1" "Пожелание": Пожелание
"Тэг пожелания" "*" -- "1" "Тэг": Тэг
"Новостной канал" "*" -- "1" "Язык": Язык
"Позиция в новостном канале" "*" -- "1" "Новостной канал": Новостной канал
"Подписка проекта на новости" "*" -- "1" "Новостной канал": Новостной канал
"Подписка проекта на новости" "*" -- "1" "Проект": Проект
"Ежедневный митинг" "*" -- "1" "Участник": Участник
"Участие в митинге" "*" -- "1" "Митинг": Митинг
"Участие в митинге" "*" -- "1" "Участник": Участник
"Заметка к релизу" "*" -- "1" "Итерация": Релиз
"Заметка к релизу" "*" -- "1" "Пожелание": Пожелание
"Позиция опросника" "*" -- "1" "Опросник": Опрос
"Результат опроса" "*" -- "1" "Опросник": Опрос
"Результат опроса" "*" -- "1" "Пользователь": Пользователь
"Позиция результата опроса" "*" -- "1" "Позиция опросника": Позиция опросника
"Позиция результата опроса" "*" -- "1" "Результат опроса": Результат опроса
"Тэг проекта" "*" -- "1" "Проект": Проект
"Вакансия в проекте" "*" -- "1" "Проект": Проект
"Приглашение в проект" "*" -- "1" "Проект": Проект
"Приглашение в проект" "*" -- "1" "Пользователь": Автор
"Загрузивший пользователь" "*" -- "1" "Пользователь": Пользователь
"Загрузивший пользователь" "*" -- "1" "Загрузка артефакта": Загрузка артефакта
"Настройки бюджетирования" "*" -- "1" "Проект": Проект
"Настройки бюджетирования" "*" -- "1" "Валюта": Валюта проекта
"Настройки бюджетирования" "*" -- "1" "Модель оплаты": Модель оплаты
"Изменение сообщения блога" "*" -- "1" "Сообщение блога": Сообщение блога
"Изменение сообщения блога" "*" -- "1" "Пользователь": Автор
