class "Очередь сообщений" {
  Название: varchar
  Описание: largetext
  Отправитель: text
  Почтовый ящик: text
}

class "Адресат очереди сообщений" {
  Адрес получателя: text
  Очередь сообщений: Object
  Пользователь: integer
}

class "Язык" {
  Название: varchar
  Кодовое значение: text
}

class "Резервная копия" {
  Описание: varchar
  Имя файла: text
}

class "Обновление" {
  Номер: varchar
  Описание: largetext
  Имя файла: text
  Имя файла протокола: text
}

class "Настройки системы" {
  Название компании: varchar
  Язык интерфейса: Object
  text(1374): text
  Разрешать изменение логина и пароля пользователя: char
  Проект по администрированию: Object
}

class "Пользователь" {
  Имя: varchar
  E-mail: varchar
  Логин: varchar
  Язык: Object
  ICQ: text
  Skype: text
  Телефон: text
  Пароль: text
  Может участвовать в нескольких проектах: char
  Является администратором: char
  Хеш сессии: text
  Фотография: image
  Активирован: char
  Рейтинг: float
  Описание: largetext
  Идентификатор LDAP: text
}

class "Лицензия" {
  Тип: text
  Значение: text
  Ключ: text
}

class "Черный список" {
  Пользователь: Object
  IP: text
  Причина блокировки: text
}

class "Параметры задачи" {
  Название задачи: varchar
  Параметры: largetext
}

class "Временный файл" {
  Название: varchar
  Имя файла: text
  MIME тип: text
  Файл: file
}

class "Задание по расписанию" {
  Назначение: varchar
  Класс: text
  Параметры: largetext
  Минуты: varchar
  Часы: varchar
  Дни месяца: varchar
  Дни недели: varchar
  Задание активно: char
}

class "Выполнение задания" {
  Задание: Object
  Результат: largetext
  Выполнено: char
}

class "Группа проектов" {
  Название: varchar
  Описание: largetext
  Входит в группу: Object
  Идентификатор LDAP: text
}

class "Проект в группе" {
  Группа: Object
  Проект: Object
}

class "Группа пользователей" {
  Название: varchar
  Описание: largetext
  Входит в группу: Object
  Идентификатор LDAP: text
}

class "Пользователь в группе" {
  Группа: Object
  Пользователь: Object
}

class "Право доступа" {
  Группа: Object
  Тип объекта: text
  Объект: varchar
  Право доступа: text
}

class "Ресурс" {
  Ключ: text
  Значение: text
}

class "Пользовательский отчет" {
  Название: varchar
  Базовый отчет: text
  Параметры: text
  Описание: largetext
  Автор: Object
}

class "Проверка" {
  Название: varchar
  Описание: largetext
  Результат проверки: char
  Включена: char
  Значение: text
}

class "Тип почтового ящика" {
  Название: varchar
  Протокол: text
}

class "Транспорт почты" {
  Название: varchar
  Ссылочное имя: varchar
}

"Адресат очереди сообщений" "*" -- "1" "Очередь сообщений": Очередь сообщений
"Настройки системы" "*" -- "1" "Язык": Язык интерфейса
"Настройки системы" "*" -- "0..1" "Проект": Проект по администрированию
"Пользователь" "*" -- "1" "Язык": Язык
"Черный список" "*" -- "1" "Пользователь": Пользователь
"Выполнение задания" "*" -- "1" "Задание по расписанию": Задание
"Группа проектов" "*" -- "0..1" "Группа проектов": Входит в группу
"Проект в группе" "*" -- "1" "Группа проектов": Группа
"Проект в группе" "*" -- "1" "Проект": Проект
"Группа пользователей" "*" -- "0..1" "Группа пользователей": Входит в группу
"Пользователь в группе" "*" -- "1" "Группа пользователей": Группа
"Пользователь в группе" "*" -- "1" "Пользователь": Пользователь
"Право доступа" "*" -- "1" "Группа пользователей": Группа
"Пользовательский отчет" "*" -- "1" "Пользователь": Автор
