class "Атрибут состояния" {
  Состояние: Object
  Атрибут: varchar
  Сущность: varchar
  Видимо на форме: char
  Обязательно для заполнения: char
}

class "Аккаунт в СКВ" {
  Пользователь: Object
  Подключение: Object
  Имя пользователя: varchar
  Пароль: password
}

class "Изменненные объекты" {
  Объект: integer
  Класс: varchar
}

class "Изменившиеся атрибуты" {
  Изменение: Object
  Атрибуты: text
}

class "Состояние" {
  Название: varchar
  Описание: largetext
  Кодовое имя: varchar
  Сущность: text
  Цвет: color
  Является терминальным: char
  Количество объектов: integer
}

class "Переход в состояние" {
  Название: varchar
  Описание: largetext
  Исходное состояние: Object
  Целевое состояние: Object
  Необходимо указать причину перехода: char
}

class "Состояние объекта" {
  Ид объекта: integer
  Класс объекта: text
  Состояние: Object
  Комментарий: largetext
  Переход: Object
  Автор: Object
  Продолжительность: float
}

class "Право доступа на переход" {
  Переход: Object
  Роль: Object
}

class "Атрибуты перехода" {
  Переход: Object
  Атрибут: varchar
  Сущность: largetext
}

class "Предикат" {
  Название: varchar
}

class "Предусловие на переход" {
  Переход: Object
  Предикат: Object
}

class "Очищаемое поле" {
  Переход: Object
  Атрибут: varchar
  Сущность: text
}

class "Дополнительные действия" {
  Название: varchar
  Ссылочное имя: varchar
  Состояние: Object
}

"Атрибут состояния" "*" -- "1" "Состояние": Состояние
"Аккаунт в СКВ" "*" -- "1" "Пользователь": Пользователь
"Аккаунт в СКВ" "*" -- "1" "text(1058)": Подключение
"Изменившиеся атрибуты" "*" -- "1" "Изменение объекта": Изменение
"Переход в состояние" "*" -- "1" "Состояние": Исходное состояние
"Переход в состояние" "*" -- "1" "Состояние": Целевое состояние
"Состояние объекта" "*" -- "1" "Состояние": Состояние
"Состояние объекта" "*" -- "0..1" "Переход в состояние": Переход
"Состояние объекта" "*" -- "1" "Пользователь": Автор
"Право доступа на переход" "*" -- "1" "Переход в состояние": Переход
"Право доступа на переход" "*" -- "1" "Роль в проекте": Роль
"Атрибуты перехода" "*" -- "1" "Переход в состояние": Переход
"Предусловие на переход" "*" -- "1" "Переход в состояние": Переход
"Предусловие на переход" "*" -- "1" "Предикат": Предикат
"Очищаемое поле" "*" -- "1" "Переход в состояние": Переход
"Дополнительные действия" "*" -- "1" "Состояние": Состояние
