class "Тест" {
  Тестовый сценарий: Object
  Окружение: Object
  Версия: varchar
  Результат: Object
}

class "Проверка тестового случая" {
  Тест: Object
  Тестовый случай: Object
  Успешный результат: char
  Тестировал: Object
  Результат: Object
  Описание: text
}

class "Окружение" {
  Название: varchar
  Описание: richtext
}

class "Тест план" {
  Название: varchar
  Описание: richtext
}

class "Позиция тест плана" {
  Тестовый набор: Object
  Тестировщик: Object
  Планируемая трудоемкость: float
  Тест план: Object
}

class "Результат тестирования" {
  Название: varchar
  Ссылочное имя: varchar
}

"Тест" "*" -- "1" "": Тестовый сценарий
"Тест" "*" -- "0..1" "Окружение": Окружение
"Тест" "*" -- "1" "Результат тестирования": Результат
"Проверка тестового случая" "*" -- "1" "Тест": Тест
"Проверка тестового случая" "*" -- "1" "Wiki страница": Тестовый случай
"Проверка тестового случая" "*" -- "1" "Участник": Тестировал
"Проверка тестового случая" "*" -- "1" "Результат тестирования": Результат
"Позиция тест плана" "*" -- "1" "Wiki страница": Тестовый набор
"Позиция тест плана" "*" -- "0..1" "Участник": Тестировщик
"Позиция тест плана" "*" -- "1" "Тест план": Тест план
