<?php
include "ProjectDashboardList.php";

class ProjectDashboardTable extends PMPageTable
{
	function getList() {
		return new ProjectDashboardList( $this->object );
	}

	function getFilters()
    {
        return array_merge(
            parent::getFilters(),
            array (
                $this->buildStateFilter()
            )
        );
    }

    function getFilterPredicates()
	{
	    $values = $this->getFilterValues();
	    return array_merge(
	        parent::getFilterPredicates(),
            array(
                new ProjectStatePredicate($values['state'])
	        )
        );
	}

	function getSortDefault($sort_parm = 'sort')
    {
        if ( $sort_parm == 'sort' ) {
            return 'Importance.A';
        }
        return parent::getSortDefault($sort_parm); // TODO: Change the autogenerated stub
    }

    protected function buildProjectFilter() {
        return null;
    }

    function buildStateFilter()
    {
        $filter = new FilterObjectMethod(getFactory()->getObject('ProjectState'), '', 'state');
        $filter->setIdFieldName('ReferenceName');
        $filter->setHasNone(false);
        $filter->setType('singlevalue');
        $filter->setDefaultValue('active');
        return $filter;
    }
}