<?php

class ProjectMetricsList extends PMPageList
{
    function buildIterator()
    {
        $this->getObject()->setRegistry( new ObjectRegistrySQL() );
        return parent::buildIterator(); // TODO: Change the autogenerated stub
    }

    function getGroupDefault() {
        return 'none';
    }

    function getReferenceIt( $attribute  )
    {
        switch( $attribute ) {
            case 'Metric':
                return getFactory()->getObject('Metric')->getAll();
            default:
                return parent::getReferenceIt($attribute);
        }
    }
}
