imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:
        fallback: en
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/Resources/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    #csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: "%systemLanguage%"
    trusted_proxies: ~
    session:
        name: sdsessid
        cookie_lifetime: 0
        gc_maxlifetime: 604800
        save_path: ~

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 9.4
        driver:   "%database_driver%"
        host:     "%DB_HOST%"
        port:     "%database_port%"
        dbname:   "%DB_NAME%"
        user:     "%DB_USER%"
        password: "%DB_PASS%"
        charset:  "%APP_CHARSET%"
        driver_class: Devprom\CommonBundle\Doctrine\DBAL\Driver\PDOMySql\Driver
        types:
            datetime: Devprom\CommonBundle\Doctrine\DBAL\Type\UTCDateTimeType
        options:
            x_reconnect_attempts: 10
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

twig:
    globals:
        registration_enabled: '%registration_enabled%'
        resetting_enabled: '%resetting_enabled%'
    form_themes:
        - DevpromServiceDeskBundle:Form:fields.html.twig

monolog:
    handlers:
        applog:
            type: rotating_file
            path: "%kernel.logs_dir%/servicedesk_system.log"
            level: debug
            max_files: 5 # Set up to keep log files for 5 recent days only
