
# Security routes ---------------------------

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Business routes ---------------------------

devprom_service_desk_language:
    resource: "@DevpromServiceDeskBundle/Controller/LanguageController.php"
    type: annotation

devprom_service_desk_attachment:
    resource: "@DevpromServiceDeskBundle/Controller/AttachmentController.php"
    type: annotation

devprom_service_desk_settings:
    resource: "@DevpromServiceDeskBundle/Controller/SettingsController.php"
    type: annotation

devprom_service_desk_issue:
    resource: "@DevpromServiceDeskBundle/Controller/IssueController.php"
    type: annotation

devprom_service_desk_docs:
    resource: "@DevpromServiceDeskBundle/Controller/KnowledgeController.php"
    type: annotation

