fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Devprom\ServiceDeskBundle\Entity\User
    from_email:
        address: "%adminEmail%"
        sender_name: "%supportName%"
    service:
        mailer: servicedesk_mailer
    registration:
        confirmation:
            enabled: true
            template: DevpromServiceDeskBundle:Registration:confirmation.html.twig
        form:
            validation_groups:  [ServiceDeskRegistration, Default]
    resetting:
        email:
            template: DevpromServiceDeskBundle:Resetting:email.html.twig

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            simple_preauth:
                authenticator: apikey_authenticator
            form_login:
                provider: fos_userbundle
                default_target_path: /issues
                always_use_default_target_path: true
            logout:       true
            anonymous:    true
            http_basic:   false
            remember_me:
                secret:   servicedesk_registration_form
                path:     /
                always_remember_me: false

    access_control:
        - { path: ^/css, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lang, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/settings, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/issue, roles: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

