fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Devprom\ServiceDeskBundle\Entity\User
    service:
        mailer: servicedesk_mailer
    registration:
        form:
            type: servicedesk_registration_form
            validation_groups:  [ServiceDeskRegistration, Default]
    resetting:
        email:
            template: DevpromServiceDeskBundle:Resetting:email.html.twig
            from_email:
                address: "%adminEmail%"
                sender_name: "%supportName%"

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                always_use_default_target_path: true
                default_target_path: /issues
            logout:       true
            anonymous:    true
            http_basic:   false
            remember_me:
                key:      servicedesk_registration_form
                lifetime: 31536000
                path:     /

    access_control:
        - { path: ^/css, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lang, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/settings, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/issue, roles: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

