services:
    apikey_authenticator:
        class:  Devprom\ServiceDeskBundle\Security\ApiKeyAuthenticator
        arguments:
            $em: "@doctrine.orm.entity_manager"
        public: false

    doctrine_dbal_connection_listener:
        class: Devprom\CommonBundle\Doctrine\DBAL\Listener\PostConnectListener
        tags:
            - { name: doctrine.event_listener, event: postConnect }
            
    object_change_logger:
        class: Devprom\ServiceDeskBundle\Service\ObjectChangeLogger
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $translator: "@translator"

    servicedesk_twig_unescapehtml:
        class: Devprom\ServiceDeskBundle\Twig\UnescapeHtmlTwigExtention
        tags:
            - { name: twig.extension }

    servicedesk_twig_issuetype:
        class: Devprom\ServiceDeskBundle\Twig\IssueTypeTwigExtention
        tags:
            - { name: twig.extension }

    servicedesk_twig_localedate:
        class: Devprom\ServiceDeskBundle\Twig\LocaleDateTwigExtention
        arguments:
            $stack: "@request_stack"
        tags:
            - { name: twig.extension }

    servicedesk_twig_assetpath:
        class: Devprom\ServiceDeskBundle\Twig\AssetPathTwigExtension
        tags:
            - { name: twig.extension }

    servicedesk_twig_wysiwyg:
        class: Devprom\ServiceDeskBundle\Twig\WysiwygTwigExtention
        arguments:
            $container: "@service_container"
        tags:
            - { name: twig.extension }

    servicedesk_twig_single_wysiwyg:
        class: Devprom\ServiceDeskBundle\Twig\WysiwygSingleTwigExtention
        arguments:
            $container: "@service_container"
        tags:
            - { name: twig.extension }

    servicedesk_twig_show_attribute:
        class: Devprom\ServiceDeskBundle\Twig\ShowAttributeTwigExtention
        arguments:
            $container: "@service_container"
        tags:
            - { name: twig.extension }

    servicedesk_twig_text_wysiwyg:
        class: Devprom\ServiceDeskBundle\Twig\WysiwygTextTwigExtention
        arguments:
            $container: "@service_container"
        tags:
            - { name: twig.extension }

    servicedesk_twig_settings:
        class: Devprom\ServiceDeskBundle\Twig\SettingsTwigExtension
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $router: "@router"
        tags:
            - { name: twig.extension }

    request_listener:
            class: Devprom\ServiceDeskBundle\EventListener\RequestListener
            arguments:
                $tokenStorage: "@security.token_storage"
                $twig: "@twig"
                $defaultLocale: "%locale%"
            tags:
                - { name: kernel.event_subscriber }

    user_registered_listener:
            class: Devprom\ServiceDeskBundle\EventListener\UserRegisteredListener
            arguments:
                $userService: "@user_service"
                $objectChangeLogger: "@object_change_logger"
            tags:
                - { name: kernel.event_subscriber }

    model_factory:
        class: ModelFactory

    user_service:
        class: Devprom\ServiceDeskBundle\Service\UserService
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $userManager: "@fos_user.user_manager"
            $mailer: "@servicedesk_mailer"
            $objectChangeLogger: "@object_change_logger"

    issue_service:
        class: Devprom\ServiceDeskBundle\Service\IssueService
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $objectChangeLogger: "@object_change_logger"
            $mailer: "@servicedesk_mailer"

    issue_attachment_service:
        class: Devprom\ServiceDeskBundle\Service\IssueAttachmentService
        arguments:
            $em: "@doctrine.orm.entity_manager"

    knowledge_service:
        class: Devprom\ServiceDeskBundle\Service\KnowledgeService
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $tokenStorage: "@security.token_storage"

    comment_attachment_service:
        class: Devprom\ServiceDeskBundle\Service\CommentAttachmentService
        arguments:
            $em: "@doctrine.orm.entity_manager"

    settings_service:
        class: Devprom\ServiceDeskBundle\Service\SettingsService
        arguments:
            $kernel: "@kernel"
            $settingsStorage: "@settings_storage"
            $settingsFilter: "@settings_filter"
            $settingsFilePath: "@@DevpromServiceDeskBundle/Resources/config/settings.yml"
            $acceptedSettings: "%accepted_settings%"

    settings_storage:
        class: Devprom\ServiceDeskBundle\Service\YamlSettingsStorage

    settings_filter:
        class: Devprom\ServiceDeskBundle\Service\SettingsFilter
        arguments:
            $acceptedSettings: "%accepted_settings%"

    servicedesk_mailer:
        class: Devprom\ServiceDeskBundle\Mailer\Mailer
        arguments:
            $mailer: "@mailer"
            $router: "@router"
            $twig: "@twig"
            $parameters:
                em: "@doctrine.orm.entity_manager"
                template:
                    confirmation: "%fos_user.registration.confirmation.template%"
                    resetting: "%fos_user.resetting.email.template%"
                    registration: DevpromServiceDeskBundle:Registration:email.html.twig
                from_email:
                    confirmation: "%fos_user.registration.confirmation.from_email%"
                    resetting: "%fos_user.resetting.email.from_email%"
                    default:
                        address: "%adminEmail%"
                        sender_name: "%supportName%"

    servicedesk_type_entity_hidden:
        class: Devprom\ServiceDeskBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: entity_hidden }
    
    clear_cache_service:
        class: Devprom\CommonBundle\Service\ClearCacheService
        arguments:
            $cacheDir: "%kernel.cache_dir%"

    form_issue_edit:
        class: Devprom\ServiceDeskBundle\Form\Type\IssueFormType
        arguments: ["@doctrine.orm.entity_manager", "@translator"]
        tags:
            - { name: form.type }

    form_issue_feedback:
        class: Devprom\ServiceDeskBundle\Form\Type\IssueFeedbackFormType
        arguments: ["@doctrine.orm.entity_manager", "@translator"]
        tags:
            - { name: form.type }

    registration_complete:
        class: Devprom\ServiceDeskBundle\EventListener\RegistrationConfirmListener
        arguments: ["@router","@user_service"]
        tags:
            - { name: kernel.event_subscriber }

    user_logged_listener:
        class: Devprom\ServiceDeskBundle\EventListener\UserLoggedListener
        arguments:
            $userService: "@user_service"
            $objectChangeLogger: "@object_change_logger"
        tags:
            - { name: kernel.event_subscriber }
