entry:
  path: /
  defaults: { _controller: MobileAppBundle:App:entry }

whatsnew:
  path: /whatsnew
  defaults: { _controller: MobileAppBundle:App:whatsnew }

workitems:
  path: /workitems
  defaults: { _controller: MobileAppBundle:App:workitems }

comments:
  path: /comments
  defaults: { _controller: MobileAppBundle:App:comments }

people:
  path: /people
  defaults: { _controller: MobileAppBundle:App:people }

projects:
  path: /projects
  defaults: { _controller: MobileAppBundle:App:projects }

builds:
  path: /builds
  defaults: { _controller: MobileAppBundle:App:builds }

tests:
  path: /tests
  defaults: { _controller: MobileAppBundle:App:tests }

form:
  path: /form/{className}/{objectId}
  defaults: { _controller: MobileAppBundle:App:form }
  methods:  GET

form_process:
  path: /form/{className}/{objectId}
  defaults: { _controller: MobileAppBundle:App:formProcess }
  methods:  POST

form_dismiss:
  path: /form/{className}/{objectId}
  defaults: { _controller: MobileAppBundle:App:formDismiss }
  methods:  DELETE

comment_process:
  path: /comment/{className}/{objectId}
  defaults: { _controller: MobileAppBundle:App:commentProcess }
  methods:  POST

wiki:
  path: /wiki/{className}
  defaults: { _controller: MobileAppBundle:App:wiki }

heirarchy:
  path: /hierarchy/{className}/{objectId}
  defaults: { _controller: MobileAppBundle:App:hierarchy }
